substitutions:
  name: dbk
  friendly_name: DBK
  device_id: DBK
  name_add_mac_suffix: "true"
  project_version: "0.1.0"
  good_limit: "25"
  fair_limit: "50"
  splash_seconds: "3"
  wifi_ap_timeout_seconds: "90"
  wifi_ap_active_timeout_minutes: "15"
  wifi_reboot_timeout: "990s"
  timezone: "Asia/Bangkok"
  warmup_seconds: "30"
  stale_seconds: "10"

packages:
  board: !include packages/board.yaml
  connectivity: !include packages/connectivity.yaml
  pms7003: !include packages/pms7003.yaml
  status_led: !include packages/status-led.yaml
  oled: !include packages/oled.yaml
  diagnostics: !include packages/diagnostics.yaml
