#!/usr/bin/env python3
"""Generate and locally compile one ESPHome image per Canvas example.

The browser gallery and the firmware catalog deliberately share their source:
the three basic lambdas are extracted from the simulator HTML, while the 30
original designs are indexed from oled-gallery-screens.js and rendered by the
already hardware-compiled switch in sim/gallery.yaml.  Generated YAML files are
checked in so every flash button has a readable, independently compilable input.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import time


ROOT = Path(__file__).resolve().parents[1]
SIMULATOR = ROOT / "site/tools/esphome-canvas-simulator.html"
GALLERY_JS = ROOT / "site/tools/oled-gallery-screens.js"
YAML_DIR = ROOT / "sim/canvas"
FIRMWARE_DIR = ROOT / "site/firmware/canvas"
MANIFEST_DIR = ROOT / "site/manifests/canvas"
CATALOG_PATH = YAML_DIR / "catalog.json"
ARTIFACT_CATALOG_PATH = FIRMWARE_DIR / "catalog.json"
ACTIVE_CONFIG = YAML_DIR / "_active.yaml"
DEVICE_NAME = "dbk-canvas"
BASIC_IDS = ("readings", "animation", "geometry")
BASIC_NAMES = {
    "readings": "DBK Readings",
    "animation": "Animated Sweep",
    "geometry": "Geometry Test",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def gallery_examples() -> list[dict[str, object]]:
    source = GALLERY_JS.read_text()
    matches = re.findall(
        r"\{\s*id:\s*\"([^\"]+)\",\s*name:\s*\"([^\"]+)\"",
        source,
    )
    if len(matches) != 30:
        raise SystemExit(f"expected 30 gallery screens, found {len(matches)}")
    return [
        {"id": screen_id, "name": name, "kind": "gallery", "screen_index": index}
        for index, (screen_id, name) in enumerate(matches)
    ]


def browser_basic_yaml() -> dict[str, str]:
    source = SIMULATOR.read_text()
    start = source.index("  var EXAMPLES = {")
    end = source.index("\n  };", start)
    block = source[start:end]
    found: dict[str, str] = {}
    for example_id in BASIC_IDS:
        match = re.search(rf"\n\s*{re.escape(example_id)}:\s*`(.*?)`\s*(?:,|\Z)", block, re.S)
        if not match:
            raise SystemExit(f"could not extract browser YAML for {example_id}")
        found[example_id] = match.group(1)
    return found


def extract_lambda(yaml_text: str) -> tuple[list[str], str | None]:
    lines = yaml_text.splitlines()
    lambda_line = next(i for i, line in enumerate(lines) if re.search(r"lambda:\s*\|-?", line))
    key_indent = len(lines[lambda_line]) - len(lines[lambda_line].lstrip())
    body: list[str] = []
    for line in lines[lambda_line + 1 :]:
        indent = len(line) - len(line.lstrip())
        if line.strip() and indent <= key_indent:
            break
        body.append(line)
    base = min(len(line) - len(line.lstrip()) for line in body if line.strip())
    body = [line[base:] if line.strip() else "" for line in body]
    interval_match = re.search(r"^\s*update_interval:\s*([^\s#]+)", yaml_text, re.M)
    return body, interval_match.group(1) if interval_match else None


def all_examples() -> list[dict[str, object]]:
    basics = [
        {"id": example_id, "name": BASIC_NAMES[example_id], "kind": "basic", "screen_index": None}
        for example_id in BASIC_IDS
    ]
    return basics + gallery_examples()


def wrapper_yaml(example: dict[str, object], basics: dict[str, str]) -> str:
    example_id = str(example["id"])
    name = str(example["name"])
    index = example["screen_index"]
    selected = int(index) if index is not None else 0
    lines = [
        "# Generated by tools/canvas-firmware.py; edit the Canvas source, not this file.",
        f"# Canvas example: {name} ({example_id})",
        "substitutions:",
        f"  device_name: {DEVICE_NAME}",
        "  friendly_name: DBK Canvas",
        f"  initial_screen: '{selected}'",
        f"  selected_screen: '{selected}'",
        "packages:",
        "  hardware_and_gallery: !include ../gallery.yaml",
    ]
    if example["kind"] == "basic":
        body, interval = extract_lambda(basics[example_id])
        lines.extend(["display:", "- id: !extend oled"])
        if interval:
            lines.append(f"  update_interval: {interval}")
        lines.extend(["  lambda: |-", *[f"    {line}" if line else "" for line in body]])
    return "\n".join(lines) + "\n"


def generate() -> list[dict[str, object]]:
    examples = all_examples()
    basics = browser_basic_yaml()
    YAML_DIR.mkdir(parents=True, exist_ok=True)
    (YAML_DIR / ".gitignore").write_text("/.esphome/\n/_active.yaml\n")
    for example in examples:
        (YAML_DIR / f"{example['id']}.yaml").write_text(wrapper_yaml(example, basics))
    catalog = {
        "schema_version": 1,
        "device": "ESP32-C3 + SSD1306 128x32",
        "source": "site/tools/esphome-canvas-simulator.html",
        "examples": examples,
    }
    CATALOG_PATH.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n")
    return examples


def manifest(example: dict[str, object], compiler_version: str) -> dict[str, object]:
    example_id = str(example["id"])
    return {
        "name": f"DustBoy Canvas - {example['name']}",
        "version": f"{compiler_version}-local-canvas",
        "new_install_prompt_erase": False,
        "builds": [
            {
                "chipFamily": "ESP32-C3",
                "parts": [
                    {"path": f"../../firmware/canvas/{example_id}.factory.bin", "offset": 0}
                ],
            }
        ],
    }


def compiler_version(command: str) -> str:
    result = subprocess.run([command, "version"], check=True, text=True, capture_output=True)
    match = re.search(r"Version:\s*([^\s]+)", result.stdout + result.stderr)
    return match.group(1) if match else "unknown"


def locate_factory_binary() -> Path:
    build_root = YAML_DIR / ".esphome/build" / DEVICE_NAME
    candidates = list(build_root.glob(f".pioenvs/{DEVICE_NAME}/firmware.factory.bin"))
    if len(candidates) != 1:
        raise SystemExit(f"expected one factory binary below {build_root}, found {candidates}")
    return candidates[0]


def build(
    examples: list[dict[str, object]], command: str, only: set[str], verbose: bool
) -> None:
    selected = [example for example in examples if not only or str(example["id"]) in only]
    unknown = only - {str(example["id"]) for example in examples}
    if unknown:
        raise SystemExit(f"unknown example ids: {', '.join(sorted(unknown))}")
    version = compiler_version(command)
    print(f"ESPHome {version}; compiling {len(selected)} Canvas firmware images")
    FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST_DIR.mkdir(parents=True, exist_ok=True)
    seen_hashes: dict[str, str] = {}
    records: list[dict[str, object]] = []
    env = dict(os.environ, COPYFILE_DISABLE="1")
    log_dir = YAML_DIR / ".esphome/logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    try:
        for number, example in enumerate(selected, 1):
            example_id = str(example["id"])
            config = YAML_DIR / f"{example_id}.yaml"
            # Compile every variant through one stable path. ESPHome can then keep
            # the shared PlatformIO build cache instead of treating each checked-in
            # wrapper filename as a separate device configuration.
            ACTIVE_CONFIG.write_text(config.read_text())
            started = time.time()
            print(f"\n[{number}/{len(selected)}] {example_id}: {example['name']}")
            build_command = [command, "compile", str(ACTIVE_CONFIG)]
            if verbose:
                subprocess.run(build_command, cwd=ROOT, env=env, check=True)
            else:
                log_path = log_dir / f"{example_id}.log"
                with log_path.open("w") as log:
                    result = subprocess.run(
                        build_command,
                        cwd=ROOT,
                        env=env,
                        text=True,
                        stdout=log,
                        stderr=subprocess.STDOUT,
                    )
                if result.returncode:
                    tail = "\n".join(log_path.read_text(errors="replace").splitlines()[-80:])
                    raise SystemExit(f"compile failed for {example_id}:\n{tail}")
            source = locate_factory_binary()
            target = FIRMWARE_DIR / f"{example_id}.factory.bin"
            if source.stat().st_mtime + 1 < started:
                if not target.exists() or sha256(target) != sha256(source):
                    raise SystemExit(f"stale build artifact after compiling {example_id}: {source}")
                print(f"reused freshly archived local build for unchanged {example_id}")
            shutil.copy2(source, target)
            digest = sha256(target)
            if digest in seen_hashes:
                raise SystemExit(f"{example_id} duplicated firmware for {seen_hashes[digest]} ({digest})")
            seen_hashes[digest] = example_id
            manifest_path = MANIFEST_DIR / f"{example_id}.json"
            manifest_path.write_text(
                json.dumps(manifest(example, version), ensure_ascii=False, indent=2) + "\n"
            )
            record = {
                **example,
                "yaml": f"sim/canvas/{example_id}.yaml",
                "manifest": f"site/manifests/canvas/{example_id}.json",
                "firmware": f"site/firmware/canvas/{example_id}.factory.bin",
                "bytes": target.stat().st_size,
                "sha256": digest,
            }
            records.append(record)
            print(f"archived {target.relative_to(ROOT)} ({record['bytes']} bytes, {digest})")
    finally:
        ACTIVE_CONFIG.unlink(missing_ok=True)

    if only:
        return
    ARTIFACT_CATALOG_PATH.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "compiler": f"ESPHome {version}",
                "count": len(records),
                "examples": records,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n"
    )


def verify(examples: list[dict[str, object]]) -> None:
    expected_ids = {str(example["id"]) for example in examples}
    catalog = json.loads(ARTIFACT_CATALOG_PATH.read_text())
    records = catalog["examples"]
    actual_ids = {record["id"] for record in records}
    if actual_ids != expected_ids or catalog["count"] != len(examples):
        raise SystemExit("artifact catalog does not cover every Canvas example")
    for record in records:
        firmware = ROOT / record["firmware"]
        config = ROOT / record["yaml"]
        manifest_path = ROOT / record["manifest"]
        if not firmware.exists() or not config.exists() or not manifest_path.exists():
            raise SystemExit(f"missing artifact for {record['id']}")
        if firmware.stat().st_size != record["bytes"] or sha256(firmware) != record["sha256"]:
            raise SystemExit(f"firmware integrity mismatch for {record['id']}")
        if firmware.read_bytes()[:1] != b"\xe9":
            raise SystemExit(f"invalid ESP image magic for {record['id']}")
        part = json.loads(manifest_path.read_text())["builds"][0]["parts"][0]
        if part["offset"] != 0 or part["path"] != f"../../firmware/canvas/{record['id']}.factory.bin":
            raise SystemExit(f"manifest mismatch for {record['id']}")
    print(f"verified {len(records)} YAML + manifest + factory-binary sets")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate-only", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--only", action="append", default=[], metavar="ID")
    parser.add_argument("--esphome", default=os.environ.get("ESPHOME_CMD", "esphome"))
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()
    examples = generate()
    if args.verify:
        verify(examples)
    elif not args.generate_only:
        build(examples, args.esphome, set(args.only), args.verbose)


if __name__ == "__main__":
    main()
